### ISSUE TITLE
#00 Vídeo indisponível

### ISSUE THREAD

**Issue by gabrielferreiraa** [lukinco/semana-hacktoberfest#1]
O `embed` do vídeo do Youtube no site está dando como indisponível, provavelmente é alguma configuração no canal/vídeo que habilite esta permissão de fazer incorporação deste vídeo fora do domínio do Youtube 😄 

![Screen Shot 2020-09-23 at 00 55 08](https://user-images.githubusercontent.com/17201177/93965039-753a3900-fd37-11ea-96bd-948c95cdc148.png)

**Comment by vmarcosp** [comment]
Opa! Valeu por avisar @gabrielferreiraa! @fdaciuk sabe o que pode ter rolado nisso?

**Comment by fdaciuk** [comment]
Acho que é padrão do YouTube deixar desabilitada a opção de _embedding_.. mas tá resolvido :)

**Comment by fdaciuk** [comment]
Obrigado por avisar @gabrielferreiraa :D

**Comment by gabrielferreiraa** [comment]
Magina ❤️
