### ISSUE TITLE
Headings no mobile alinhados a direita

### ISSUE THREAD

**Issue by vinicius98s** [lukinco/semana-hacktoberfest#2]
Tudo bem pessoal?

Estava dando uma olhada na versão mobile do site e percebi que alguns headings continuam alinhados a direita (seguindo o layout do desktop), o que na minha visão acaba quebrando um pouco o fluxo de leitura:

![image](https://user-images.githubusercontent.com/38966428/94827634-0f0c8080-03df-11eb-95a0-7030a7cee815.png)

Sugestão: No mobile alinhar todos os headings a esquerda.

Acham que faz sentido? Estou disposto a abrir uma PR se quiserem.

**Comment by vmarcosp** [comment]
Fala @vinicius98s, valeu por reportar. Acho que pode ficar melhor mesmo, você consegue abrir um `PR`? 😄

**Comment by vinicius98s** [comment]
Opa @vmarcosp abri uma PR lá, valeu!
